module.exports = {
    header: [
        {
            name: '驾驶舱',
            iconNormal: require('../app/routes/pages/mainPage/img/comp/jsc.png'),
            iconActive: require('../app/routes/pages/mainPage/img/comp/jsc_active.png'),

            subPage: [{
                name:'运营监控',
                page:[
                    {
                        name:'数据预览',
                        page:'super',
                        
                    },{
                        name:'地理分布',
                        page:'from',
                        
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                        
                    },{
                        name:'升压站矩阵',
                        page:'chart',
                        
                    },{
                        name:'调控概览',
                        page:'table',
                        
                    },{
                        name:'集合预报',
                        page:'table',
                        
                    }]
            },{
                name:'批量监控',
                page:[
                    {
                        name:'数据预览',
                        page:'from',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'业务报表',
                page:[
                     {
                        name:'数据预览',
                        page:'table',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'故障报警',
                page:[
                     {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'故障录播',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'数据整理',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            }],
        },{
            name: '实时监控',
            iconNormal: require('../app/routes/pages/mainPage/img/comp/ssjk.png'),
            iconActive: require('../app/routes/pages/mainPage/img/comp/ssjk_active.png'),
            subPage: [{
                name:'运营监控1',
                page:[
                     {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'批量监控',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'业务报表',
                page:[
                     {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'故障报警',
                page:[
                     {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'故障录播',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'数据整理',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            }],
        },{
            name: '健康管理',
            iconNormal: require('../app/routes/pages/mainPage/img/comp/jkgl.png'),
            iconActive: require('../app/routes/pages/mainPage/img/comp/jkgl_active.png'),
            subPage: [{
                name:'批量监控1',
                page:[
                     {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'批量监控',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'业务报表',
                page:[
                     {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'故障报警',
                page:[
                     {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'故障录播',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'数据整理',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            }],
        },{
            name: '资产管理',
            iconNormal: require('../app/routes/pages/mainPage/img/comp/zcgl.png'),
            iconActive: require('../app/routes/pages/mainPage/img/comp/zcgl_active.png'),
            subPage: [{
                name:'批量监控1',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'批量监控2',
                page:[
                     {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'批量监控',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'业务报表',
                page:[
                     {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'故障报警',
                page:[
                     {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'故障录播',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'数据整理',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            }],
        },{
            name: '业务分析',
            iconNormal: require('../app/routes/pages/mainPage/img/comp/ywfx.png'),
            iconActive: require('../app/routes/pages/mainPage/img/comp/ywfx_active.png'),
            subPage: [{
                name:'批量监控1',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'批量监控',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'业务报表',
                page:[
                     {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'故障报警',
                page:[
                     {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'故障录播',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'数据整理',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'批量监控3',
                page:[
                     {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            }],
        },{
            name: '综合查询',
            iconNormal: require('../app/routes/pages/mainPage/img/comp/zhfx.png'),
            iconActive: require('../app/routes/pages/mainPage/img/comp/zhfx_active.png'),
            subPage: [{
                name:'批量监控1',
                page:[
                     {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'批量监控',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'业务报表',
                page:[
                     {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'故障报警',
                page:[
                     {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'故障录播',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'数据整理',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'批量监控3',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            }],
        },{
            name: '系统管理',
            iconNormal: require('../app/routes/pages/mainPage/img/comp/xtgl.png'),
            iconActive: require('../app/routes/pages/mainPage/img/comp/xtgl_active.png'),
            subPage: [{
                name:'批量监控1',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'批量监控',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'业务报表',
                page:[
                     {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'故障报警',
                page:[
                     {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'故障录播',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'数据整理',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            },{
                name:'批量监控3',
                page:[
                    {
                        name:'数据预览',
                        page:'chart',
                    },{
                        name:'地理分布',
                        page:'from',
                    },{
                        name:'风机光伏矩阵',
                        page:'table',
                    },{
                        name:'升压站矩阵',
                        page:'table',
                    },{
                        name:'调控概览',
                        page:'table',
                    },{
                        name:'集合预报',
                        page:'table',
                    }]
            }],
        },
    ]
};
